name: Test workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Define the environment variables for the job
    env:
      #NETLIFY_AUTH_TOKEN: "UO8Kl-kafR0bnP4uAf4sS-HsMoUupKk6FwauB85RL2I"
      #NETLIFY_SITE_ID: "5ddf8a2c-9646-47d7-b764-4f67402a241e"
      URL: https://jsonplaceholder.typicode.com/posts

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      # Add the environment variable to next.config.js using echo
      - name: Create .env.local filev with variable
        run: |
          echo "URL=${URL} WORKFLOW_RUNNING_TIME=$(date)" > .env.local

      - name: Show .env.local after creation
        run: |
          cat .env.local
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: UO8Kl-kafR0bnP4uAf4sS-HsMoUupKk6FwauB85RL2I
          NETLIFY_SITE_ID: 5ddf8a2c-9646-47d7-b764-4f67402a241e
        with:
          args: deploy --dir=out --prod
