name: Test workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      # Add the environment variable to next.config.js using echo
      - name: Create .env.local filev with variable
        run: |
          echo "URL=https://jsonplaceholder.typicode.com/posts" > .env.local

      - name: Show .env.local after creation
        run: |
          cat .env.local
          
          
      - name: Install dependencies
        run: npm install


      - name: Build
        run: npm run build
        
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: UO8Kl-kafR0bnP4uAf4sS-HsMoUupKk6FwauB85RL2I
          NETLIFY_SITE_ID: 5ddf8a2c-9646-47d7-b764-4f67402a241e
          NETLIFY_DEPLOY_TO_PROD: true
