name: Test workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Define the environment variables for the job
    env:
      URL: "https://jsonplaceholder.typicode.com/posts"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      # Add the environment variable to next.config.js using echo
      - name: Create .env.local filev with variable
        run: |
          echo "URL=${URL}" > .env.local
          echo "WORKFLOW_RUNNING_TIME='$(date)'" > .env.local

      - name: Show .env.local after creation
        run: |
          cat .env.local   
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: "UO8Kl-kafR0bnP4uAf4sS-HsMoUupKk6FwauB85RL2I"
          NETLIFY_SITE_ID: "5ddf8a2c-9646-47d7-b764-4f67402a241e"
        with:
          args: deploy --dir=out --prod
          
      # Trigger second workflow
      - name: Trigger Workflow B
        run: |
          REPO_OWNER="vitaliiharasymchuk"   # Replace with your GitHub username
          REPO_NAME="nextjs-ssg"  # Replace with your repository name

          # Replace 'manual-trigger' with the custom event type defined in the workflow B
          EVENT_TYPE="generate-pdf"

          # Replace 'YOUR_GITHUB_PERSONAL_ACCESS_TOKEN' with your GitHub personal access token
          TOKEN="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"

          # Make the POST request to trigger the workflow B
          curl -X POST "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token $TOKEN" \
               --data '{"event_type": "'"$EVENT_TYPE"'"}'
