name: Test workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Define the environment variables for the job
    env:
      URL: "https://jsonplaceholder.typicode.com/posts"
      
    steps:
      # Trigger second workflow
      - name: Trigger Workflow B
        run: |
          # Make the POST request to trigger the workflow B
          curl -X POST \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token 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" \
               -d '{"event_type": "repository_dispatch"}' \
                https://api.github.com/repos/vitaliiharasymchuk/nextjs-ssg/dispatches
