name: Test workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Define the environment variables for the job
    env:
      URL: "https://jsonplaceholder.typicode.com/posts"
      
    steps:
      # Trigger second workflow
      - name: Trigger Workflow B
        run: |
          # Make the POST request to trigger the workflow B
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/vitaliiharasymchuk/nextjs-ssg/actions/workflows/64547970/dispatches \
          -d '{"ref":"main","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'
